init_position:
  torso: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  right_arm: [0.4768, -0.0089, 0.1617, -1.9939, 0.3179, -0.0256, -0.2916]
  left_arm: [0.4706, 0.0405, -0.1765, -1.9902, 0.2878, -0.0346, -0.2912]
  head: [0.0, 0.785398]
  grippers: [0.0, 0.0]

perturb_defaults:
  base_x_range: [-0.1, 0.1]
  base_y_range: [-0.1, 0.1]
  base_yaw_range: [-0.35, 0.35]
  ee_pos_range: [-0.1, 0.1]
  ee_rot_range: [-0.35, 0.35]

mocap_base_target:
  pos: [0.0, 0.0, 0.0]
  geom:
    type: box
    size: [0.1, 0.1, 0.05]
    contype: 0
    conaffinity: 0
    rgba: [0.8, 0.2, 0.2, 0.5]
  weld:
    rby1:
      solimp: [0.99, 0.999, 0.001, 0.5, 2.0]
      solref: [0.001, 1.0]
    fine:
      solimp: [0.95, 0.99, 0.001]
      solref: [0.02, 1.0]

fine_manipulation:
  model_scale: 1.3
